[package]
name = "client_sdl3"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.5"
anyhow = "1"
gamestreaming_webrtc = { path = "../gamestreaming_webrtc" }
tokio = { version = "1", features = ["full"] }
sdl3-sys = "0.5.4"
ffmpeg-next = { version = "7.1.0" }
bytes = "1.10.1"
log = "0.4.27"
simple_logger = "5.0.0"
